# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cSQClepF1oyLvQDTC6F6LA3qZ4jLWPm2
"""

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from scipy.stats import norm
import streamlit as st

st.set_page_config(page_title="Portfolio VaR Calculator", layout="wide")

st.title("Monte Carlo Portfolio VaR Calculator")
st.markdown("Calculate Value at Risk (VaR) and Conditional VaR using Monte Carlo simulation")

# Sidebar inputs
st.sidebar.header("Portfolio Settings")

# Ticker input
default_tickers = "AAPL, MSFT, GOOGL, JPM, GS"
tickers = [t.strip().upper() for t in tickers_input.split(',')]

# Date range
col1, col2 = st.sidebar.columns(2)
start_date = col1.date_input("Start Date", pd.to_datetime('2020-01-01'))
end_date = col2.date_input("End Date", pd.to_datetime('2024-01-01'))

# Portfolio settings
initial_portfolio = st.sidebar.number_input("Portfolio Value ($)", min_value=1000, value=1000000, step=10000)
confidence_level = st.sidebar.slider("Confidence Level", min_value=0.90, max_value=0.99, value=0.95, step=0.01)
n_simulations = st.sidebar.slider("Number of Simulations", min_value=1000, max_value=50000, value=10000, step=1000)
time_horizon = st.sidebar.slider("Time Horizon (days)", min_value=1, max_value=30, value=1)

# Equal weights by default
weights = np.array([1/len(tickers)] * len(tickers))

if st.sidebar.button("Calculate VaR", type="primary"):

    with st.spinner("Downloading data..."):
        try:
            data = yf.download(tickers, start=start_date, end=end_date, progress=False)

            if len(tickers) > 1:
                data = data['Close']
            else:
                data = data[['Close']]

            returns = data.pct_change().dropna()
            portfolio_returns = (returns * weights).sum(axis=1)

            # Calculate stats
            mu = portfolio_returns.mean()
            sigma = portfolio_returns.std()

            # Monte Carlo simulation
            Z = np.random.standard_normal(n_simulations)
            simulated_returns = np.exp((mu - 0.5*sigma**2)*time_horizon + sigma*np.sqrt(time_horizon)*Z) - 1
            simulated_values = initial_portfolio * (1 + simulated_returns)

            # Calculate VaR and CVaR
            VaR_MC = np.percentile(simulated_returns, (1-confidence_level)*100)
            VaR_dollar = initial_portfolio * VaR_MC
            CVaR_MC = simulated_returns[simulated_returns <= VaR_MC].mean()
            CVaR_dollar = initial_portfolio * CVaR_MC

            # Parametric VaR
            VaR_parametric = norm.ppf(1-confidence_level, mu*time_horizon, sigma*np.sqrt(time_horizon))
            VaR_parametric_dollar = initial_portfolio * VaR_parametric

            # Display results
            st.success("Calculation complete!")

            # Metrics
            col1, col2, col3, col4 = st.columns(4)
            col1.metric("Average Daily Return", f"{mu:.4%}")
            col2.metric("Daily Volatility", f"{sigma:.4%}")
            col3.metric("Monte Carlo VaR", f"${-VaR_dollar:,.0f}", delta=f"{VaR_MC:.2%}", delta_color="inverse")
            col4.metric("CVaR (Expected Shortfall)", f"${-CVaR_dollar:,.0f}", delta=f"{CVaR_MC:.2%}", delta_color="inverse")

            # Comparison table
            st.subheader("VaR Comparison")
            comparison_df = pd.DataFrame({
                'Method': ['Monte Carlo', 'Parametric'],
                'VaR ($)': [f"${-VaR_dollar:,.2f}", f"${-VaR_parametric_dollar:,.2f}"],
                'VaR (%)': [f"{VaR_MC:.3%}", f"{VaR_parametric:.3%}"]
            })
            st.dataframe(comparison_df, use_container_width=True, hide_index=True)

            # Visualizations
            st.subheader("Simulation Results")

            tab1, tab2, tab3 = st.tabs(["Returns Distribution", "Portfolio Values", "Method Comparison"])

            with tab1:
                fig1, ax1 = plt.subplots(figsize=(12,6))
                ax1.hist(simulated_returns, bins=100, alpha=0.7, edgecolor='black', color='skyblue')
                ax1.axvline(VaR_MC, color='red', linestyle='--', linewidth=2, label=f'VaR ({confidence_level:.0%}): {VaR_MC:.2%}')
                ax1.axvline(CVaR_MC, color='orange', linestyle='--', linewidth=2, label=f'CVaR: {CVaR_MC:.2%}')
                ax1.axvline(0, color='green', linestyle='-', linewidth=1, alpha=0.5, label='Break-even')
                ax1.set_xlabel('Portfolio Returns', fontsize=12)
                ax1.set_ylabel('Frequency', fontsize=12)
                ax1.set_title(f'Monte Carlo Simulated Returns Distribution ({n_simulations:,} simulations)', fontsize=14)
                ax1.legend(fontsize=11)
                ax1.grid(alpha=0.3)
                st.pyplot(fig1)

            with tab2:
                fig2, ax2 = plt.subplots(figsize=(12,6))
                ax2.hist(simulated_values, bins=100, alpha=0.7, edgecolor='black', color='lightcoral')
                ax2.axvline(initial_portfolio + VaR_dollar, color='red', linestyle='--', linewidth=2,
                            label=f'VaR Threshold: ${initial_portfolio + VaR_dollar:,.0f}')
                ax2.axvline(initial_portfolio, color='green', linestyle='-', linewidth=1, alpha=0.5,
                            label=f'Initial: ${initial_portfolio:,.0f}')
                ax2.set_xlabel('Portfolio Value ($)', fontsize=12)
                ax2.set_ylabel('Frequency', fontsize=12)
                ax2.set_title('Distribution of Simulated Portfolio Values', fontsize=14)
                ax2.legend(fontsize=11)
                ax2.grid(alpha=0.3)
                st.pyplot(fig2)

            with tab3:
                fig3, ax3 = plt.subplots(figsize=(10,6))
                methods = ['Monte Carlo', 'Parametric']
                var_values = [-VaR_dollar, -VaR_parametric_dollar]
                ax3.bar(methods, var_values, color=['#FF6B6B', '#4ECDC4'], edgecolor='black', linewidth=1.5)
                ax3.set_ylabel('VaR (Loss in $)', fontsize=12)
                ax3.set_title('VaR Comparison: Monte Carlo vs Parametric', fontsize=14)
                ax3.grid(axis='y', alpha=0.3)
                for i, v in enumerate(var_values):
                    ax3.text(i, v + max(var_values)*0.02, f'${v:,.0f}', ha='center', fontsize=11, fontweight='bold')
                st.pyplot(fig3)

            # Explanation
            with st.expander("What do these numbers mean?"):
                st.markdown(f"""
                **Value at Risk (VaR)**: With {confidence_level:.0%} confidence, your portfolio will not lose more than **${-VaR_dollar:,.2f}** over the next {time_horizon} day(s).

                **Conditional VaR (CVaR)**: If losses exceed the VaR threshold, the expected loss is **${-CVaR_dollar:,.2f}**.

                **Monte Carlo vs Parametric**:
                - Monte Carlo simulates thousands of scenarios and makes no distribution assumptions
                - Parametric assumes normal distribution and uses a formula
                - Monte Carlo is typically more accurate for real-world portfolios with fat-tailed distributions
                """)

        except Exception as e:
            st.error(f"Error: {str(e)}")
            st.info("Make sure the tickers are valid and data is available for the selected date range.")

else:
    st.info("Adjust settings in the sidebar and click 'Calculate VaR' to run the simulation.")

    st.markdown("""
    ### How it works:

    1. **Enter your portfolio tickers** (e.g., AAPL, MSFT, GOOGL)
    2. **Select date range** for historical data
    3. **Set portfolio parameters** (value, confidence level, simulations)
    4. **Click Calculate** to run Monte Carlo simulation

    The tool will:
    - Download historical price data
    - Calculate portfolio statistics (mean return, volatility)
    - Simulate thousands of possible future scenarios using Geometric Brownian Motion
    - Calculate VaR and CVaR at your chosen confidence level
    - Compare Monte Carlo results with Parametric VaR
    """)

